### ISSUE TITLE
feature request: do not repeat-ask for compile command

### ISSUE THREAD

**Issue by r2evans** [zenitani/elisp#1]
Thanks for maintaining smart-compile!

Before I found this, I found [this](http://www.emacswiki.org/emacs/CompileCommand) (under Recompile) which asks for the compile command the first time but remembers it for subsequent compiles. Is it possible to do something similar for smart-compile? Though it's only one extra keypress, it'd be nice to "just remember and do it."

Thanks again!

**Comment by zenitani** [comment]
Hi,

(setq compilation-read-command nil)

Seiji

**Comment by r2evans** [comment]
I tried that, but when I open a different file (and have not closed the previous compilation buffer) and try it again, it does the wrong (re)compilation. Is this a limitation of emacs in that `compilation-last-buffer` is always global, and cannot be conditionally ignored? (such as when we are visiting a different source file)

(I also tried to do something similar using local variables thinking that I could do what I wanted by limiting scope, but was unable to get it to work correctly.)

Thanks, Seiji!

**Comment by zenitani** [comment]
I got it...  C-u M-x smart-compile will regenerate the buffer-local compile-command in any case.
- C-u M-x smart-compile
- (setq compilation-read-command nil)

At this point, I have no idea how to do better.
Thanks for the feedback!

Seiji

**Comment by r2evans** [comment]
Thanks, I appreciate the discussion.
