### ISSUE TITLE
File name stuck to old one, when you save buffer to a different file

### ISSUE THREAD

**Issue by boramalper** [zenitani/elisp#3]
Sorry for the title, I don't know how to explain it simply:

When you opened a file, for example `e7.c`, and wanted to create a new file with same content, so you saved this buffer as `e8.c` using `C-x C-w`. Now you want to compile `e8.c` but smart-compile tries to compile the file `e7.c` until you manually correct it.

**Comment by zenitani** [comment]
C-u M-x smart-compile or C-u (your key binding) will re-generate the compile command.  Does it help?

**Comment by boramalper** [comment]
Yes, it does. Thank you!
