### ISSUE TITLE
Update melpa recipe for smart-compile

### ISSUE THREAD

**Issue by edkolev** [zenitani/elisp#5]
Hi, I see you replaced the source of smart-compile on the wiki with a link to the file on github.

As a result, Melpa now distributes a fake file with the following contents:
```
Please visit https://github.com/zenitani/elisp/blob/master/smart-compile.el
;; Package-Version: 20170824.223

;;; smart-compile.el ends here
```

Could you update the Melpa recipe for smart-compile?

https://github.com/melpa/melpa/blob/master/recipes/smart-compile

I believe a PR to the Melpa repo should be submitted.

Thanks

**Comment by zenitani** [comment]
Thanks for letting me know this. I have requested Melpa developers to update the recipe: https://github.com/melpa/melpa/issues/4956

**Comment by edkolev** [comment]
Thank you!
